name: Blog console CI/CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.1.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.1.0
      - name: Build project
        run:
          yarn install;
          yarn build;
          mkdir dist;
          cp -r {build,seo,server.js,package.json,next.config.js,yarn.lock} dist;
      - name: Scp
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: /home/alan/www/dist
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          concurrency: 20
  deploy:
    needs: [build]
    name: Deploy console
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            cd /home/alan/www/blog-web
            ls |grep -v 'node_modules' |xargs rm -rf
            mv /home/alan/www/dist/* /home/alan/www/blog-web/
            yarn install
            pm2 restart blog-web
            rm -f /home/alan/www/dist/*

