name: Blog console CI/CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.1.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.1.0
      - name: Build project
        run:
          yarn install;
          yarn build;
          mkdir blog;
          cp -r {build,seo,server.js,package.json,next.config.js,yarn.lock} blog;
      - name: Scp
        uses: garygrossgarten/github-action-scp@release
        with:
          local: blog
          remote: /home/alan/tmp
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          concurrency: 20
  deploy:
    needs: [build]
    name: Deploy console
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            cd /home/alan/projects/blog
            ls |grep -v 'node_modules' |xargs rm -rf
            mv /home/alan/tmp/blog/* /home/alan/projects/blog
            yarn install
            pm2 restart blog
            rm -f /home/alan/tmp/blog/*

